"""empty message

Revision ID: 7cc6d3ff9399
Revises: 
Create Date: 2022-12-13 14:15:59.906191

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '7cc6d3ff9399'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('user_key', sa.Integer(), nullable=False),
    sa.Column('user_name', sa.String(length=30), nullable=False),
    sa.Column('user_email', sa.String(length=120), nullable=False),
    sa.Column('user_password', sa.String(length=30), nullable=False),
    sa.Column('user_age', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('user_key'),
    sa.UniqueConstraint('user_email'),
    sa.UniqueConstraint('user_name')
    )
    op.drop_table('3pos_user')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('3pos_user',
    sa.Column('user_key', mysql.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('user_name', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user_email', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user_password', mysql.VARCHAR(length=100), nullable=True),
    sa.Column('user_age', mysql.VARCHAR(length=100), nullable=True),
    sa.PrimaryKeyConstraint('user_key'),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('user')
    # ### end Alembic commands ###
