"""empty message

Revision ID: f7ba00fced6f
Revises: 7cc6d3ff9399
Create Date: 2022-12-13 16:33:30.536777

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f7ba00fced6f'
down_revision = '7cc6d3ff9399'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_phone', sa.String(length=30), nullable=False))
        batch_op.drop_column('user_age')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_age', mysql.INTEGER(), autoincrement=False, nullable=False))
        batch_op.drop_column('user_phone')

    # ### end Alembic commands ###
