"""empty message

Revision ID: 97e2d2f05808
Revises: c40c40b41f6d
Create Date: 2022-12-14 17:00:03.076338

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '97e2d2f05808'
down_revision = 'c40c40b41f6d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('img',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('img', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('pet_info', schema=None) as batch_op:
        batch_op.alter_column('pet_birth',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               type_=sa.String(length=120),
               existing_nullable=False)
        batch_op.alter_column('pet_bred',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               type_=sa.String(length=10),
               existing_nullable=False)
        batch_op.alter_column('profile_img',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               nullable=True,
               existing_server_default=sa.text("'default.png'"))
        batch_op.create_unique_constraint(None, ['pet_name'])
        batch_op.create_unique_constraint(None, ['pet_birth'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('pet_info', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('profile_img',
               existing_type=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               nullable=False,
               existing_server_default=sa.text("'default.png'"))
        batch_op.alter_column('pet_bred',
               existing_type=sa.String(length=10),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=100),
               existing_nullable=False)
        batch_op.alter_column('pet_birth',
               existing_type=sa.String(length=120),
               type_=mysql.VARCHAR(charset='utf8mb4', collation='utf8mb4_0900_ai_ci', length=50),
               existing_nullable=False)

    op.drop_table('img')
    # ### end Alembic commands ###
