"""empty message

Revision ID: cad036b3a370
Revises: 97e2d2f05808
Create Date: 2022-12-14 17:02:39.755715

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'cad036b3a370'
down_revision = '97e2d2f05808'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('pet_img')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('pet_img',
    sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('img', mysql.VARCHAR(length=100), nullable=False),
    mysql_collate='utf8mb4_0900_ai_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
